# Generated by Django 2.0.1 on 2018-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20180408_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='details',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='details',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
