# Generated by Django 2.0.1 on 2018-06-30 03:49

from django.db import migrations


def populate_permissions_for_atlas_app(apps, schema_editor):
    Permissions = apps.get_model('authorization', 'Permissions')
    Location = apps.get_model('atlas', 'Location')
    LocationType= apps.get_model('atlas', 'LocationType')

    permissions_qs = Permissions.objects.filter(gm_only=True, authorized_characters=None, campaigns=None)
    if len(permissions_qs) == 0:
        permission = Permissions()
        permission.save()
    else:
        permission = permissions_qs[0]

    for location in Location.objects.all():
        if location.permissions is None:
            location.permissions = permission
            location.save()

    for location_type in LocationType.objects.all():
        if location_type.permissions is None:
            location_type.permissions = permission
            location_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_auto_20180629_2348'),
        ('authorization', '0004_auto_20180629_2348'),
    ]

    operations = [
        migrations.RunPython(populate_permissions_for_atlas_app),
    ]
