# Generated by Django 2.0.1 on 2018-06-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_auto_20180629_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
    ]
