# Generated by Django 2.0.1 on 2018-06-28 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20180624_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='playercharacter',
            name='is_gm',
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_gm', to='authorization.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(related_name='campaigns', to='authorization.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='campaigns',
            field=models.ManyToManyField(to='authorization.Campaign'),
        ),
    ]
