# Generated by Django 2.0.1 on 2019-10-07 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_gm_from_cm_character(apps, schema_editor):
    """
    We want to set the gm to be a User, and previously the gm was a
    PlayerCharacter. The user would be the player of the PlayerCharacter.

    :param apps:
    :param schema_editor:
    :return:
    """
    Campaign = apps.get_model('authorization', 'Campaign')
    for campaign in Campaign.objects.all():
        campaign.gm = campaign.gm_character.player
        campaign.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0005_permissions_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='gm',
            new_name='gm_character',
        ),
        migrations.AddField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_gm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=set_gm_from_cm_character,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='gm_character',
        ),
    ]
