# Generated by Django 2.0.1 on 2019-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20191006_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='edit_permissions', to='authorization.PlayerCharacter'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='authorized_characters',
            field=models.ManyToManyField(blank=True, related_name='view_permissions', to='authorization.PlayerCharacter'),
        ),
    ]
