# Generated by Django 2.0.1 on 2019-10-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20191007_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='gm_only',
        ),
    ]
