# Generated by Django 2.0.1 on 2018-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
