# Generated by Django 2.0.1 on 2018-05-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('details', '0003_auto_20180506_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Tag',
        ),
    ]
