# Generated by Django 2.0.1 on 2018-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20180506_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='detail_text',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='source',
        ),
        migrations.AddField(
            model_name='tag',
            name='pattern',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tags',
            field=models.ManyToManyField(related_name='details', to='details.Tag'),
        ),
    ]
