# Generated by Django 2.0.1 on 2018-06-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('details', '0007_auto_20180607_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AddField(
            model_name='detail',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AddField(
            model_name='source',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
    ]
