# Generated by Django 2.0.1 on 2018-06-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20180624_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AlterField(
            model_name='source',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
    ]
