# Generated by Django 2.0.1 on 2019-02-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20180624_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='details.Chapter'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='details.Source'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='details', to='details.Tag'),
        ),
    ]
