# Generated by Django 2.0.1 on 2019-02-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20180629_2348'),
        ('details', '0011_auto_20190203_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Tag')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='RelationMemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions')),
            ],
        ),
        migrations.AddField(
            model_name='relationmember',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.RelationMemberType'),
        ),
        migrations.AddField(
            model_name='relation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='relations', to='details.RelationMember'),
        ),
        migrations.AddField(
            model_name='relation',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions'),
        ),
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.RelationType'),
        ),
    ]
