# Generated by Django 2.0.1 on 2019-02-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_tag_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_members', to='details.Tag'),
        ),
    ]
