# Generated by Django 2.0.1 on 2018-07-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0004_auto_20180629_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.Permissions')),
                ('prime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redactions', to='census.Character')),
            ],
        ),
    ]
